SELECT * FROM ref_educations;
SELECT * FROM type_pendidikan;

-- DATA PENDIDIKAN --
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (1, 'SD');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (2, 'SMP');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (3, 'SMA/Sederajat');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (4, 'D2');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (5, 'D3');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (6, 'D4');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (7, 'S1');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (8, 'S2');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (9, 'S3');
INSERT INTO type_pendidikan (id_jenis_pendidikan, jenis_pendidikan) VALUES (10, 'D1');

-- DATA JENIS PEKERJAAN --
INSERT INTO type_pekerjaan (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 1,'Belum/Tidak Bekerja');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 2,'Mengurus Rumah Tangga');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 3,'Pelajar/Mahasiswa');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 4,'Pensiunan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 5,'Pegawai Negeri Sipil (PNS)');
INSERT INTO type_pekerjaan  (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 6,'Tentara Nasional Indonesia (TNI)');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 7,'Kepolisian RI (POLRI)');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 8,'Perdagangan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan, jenis_pekerjaan) VALUES ( 9,'Petani/Pekebun');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (10,'Peternak');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (11,'Nelayan/Perikanan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (12,'Industri');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (13,'Konstruksi');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (14,'Transportasi');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (15,'Karyawan Swasta');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (16,'Karyawan BUMN');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (17,'Karyawan BUMD');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (18,'Karyawan Honorer');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (19,'Buruh Harian Lepas');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (20,'Buruh Tani/Perkebunan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (21,'Buruh Nelayan/Perikanan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (22,'Buruh Peternakan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (23,'Pembantu Rumah Tangga');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (24,'Tukang Cukur');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (25,'Tukang Listrik');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (26,'Tukang Batu');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (27,'Tukang Kayu');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (28,'Tukang Sol Sepatu');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (29,'Tukang Las/Pandai Besi');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (30,'Tukang Jahit');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (31,'Tukang Gigi');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (32,'Penata Rias');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (33,'Penata Busana');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (34,'Penata Rambut');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (35,'Mekanik');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (36,'Seniman');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (37,'Tabib');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (38,'Paraji');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (39,'Perancang Busana');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (40,'Penterjemah');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (41,'Imam Masjid');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (42,'Pendeta');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (43,'Pastor');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (44,'Wartawan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (45,'Ustadz/Mubaligh');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (46,'Juru Masak');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (47,'Promotor Acara');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (48,'Anggota DPR-RI');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (49,'Anggota DPD');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (50,'Anggota BPK');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (51,'Presiden');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (52,'Wakil Presiden');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (53,'Anggota Mahkamah');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (54,'Konstitusi');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (55,'Anggota Kabinet/Kementrian');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (56,'Duta Besar');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (57,'Gubernur');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (58,'Wakil Gubernur');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (59,'Bupati');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (60,'Wakil Bupati');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (61,'Walikota');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (62,'Wakil Walikota');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (63,'Anggota DPRD Provinsi/Kab/Kota');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (64,'Dosen');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (65,'Guru');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (66,'Pilot');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (67,'Pengacara');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (68,'Notaris');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (69,'Arsitek');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (70,'Akuntan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (71,'Konsultan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (72,'Dokter');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (73,'Bidan');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (74,'Perawat');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (75,'Apoteker');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (76,'Psikiater/Psikolog');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (77,'Penyiar Televisi');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (78,'Penyiar Radio');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (79,'Pelaut');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (80,'Peneliti');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (81,'Sopir');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (82,'Pialang');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (83,'Paranormal');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (84,'Pedagang');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (85,'Perangkat Desa');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (86,'Kepala Desa');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (87,'Biarawati');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (88,'Wiraswasta');
INSERT INTO type_pekerjaan (id_jenis_pekerjaan,  jenis_pekerjaan) VALUES (89,'Lainny');
-- Pastikan nama role SAMA dengan value di HTML option value="ADMIN"
INSERT INTO roles (id_role, nama_role) VALUES (1, 'Admin');
INSERT INTO roles (id_role, nama_role) VALUES (2, 'Asesi');
INSERT INTO roles (id_role, nama_role) VALUES (3, 'Asesor');
INSERT INTO roles (id_role, nama_role) VALUES (4, 'Direktur');

-- DATA JENIS SKEMA DAN MODE SKEMA --
INSERT INTO ref_schema_types (name) VALUES ('KKNI'), ('OKUPASI'), ('KLASTER');
INSERT INTO ref_schema_modes (name) VALUES ('Mandiri'), ('Referensi BNSP');
